logging:
  level: INFO

exchange:
 exchange.exchange_id: bybit
 testnet_mode: false

trading:
  symbol: DOT/USDT:USDT
  timeframe: 1m
  simulation_mode: false
  entry_order_type: limit
  limit_order_offset_buy: 0.0005
  limit_order_offset_sell: 0.0005
  close_positions_on_exit: false

order_book:
  depth: 10
  imbalance_threshold: 1.5

indicators:
  volatility_window: 20
  volatility_multiplier: 0.0
  ema_period: 10
  rsi_period: 14
  stoch_rsi_period: 14
  stoch_rsi_k_period: 3
  stoch_rsi_d_period: 3
  macd_short_period: 12
  macd_long_period: 26
  macd_signal_period: 9
  atr_period: 14

risk_management:
  order_size_percentage: 0.02
  max_open_positions: 1
  use_atr_sl_tp: true
  atr_sl_multiplier: 2.0
  atr_tp_multiplier: 3.0
  stop_loss_percentage: 0.005
  take_profit_percentage: 0.01
  sl_trigger_by: MarkPrice
  tp_trigger_by: MarkPrice
  enable_trailing_stop_loss: false
  trailing_stop_loss_percentage: 0.003
  time_based_exit_minutes: 60
  strong_signal_adjustment_factor: 1.0
  weak_signal_adjustment_factor: 1.0