name: Code Enhancement Workflow
on:
  workflow_dispatch:
    inputs:
      api-key:
        description: 'Gemini API Key (leave blank to use repository secret)'
        required: false
      max-api-calls:
        description: 'Maximum API calls per minute (1-60)'
        required: false
        default: '59'
      file-pattern:
        description: 'File pattern to enhance (e.g., "*.py", "src/*.py")'
        required: false
        default: '**/*.py'

jobs:
  enhance-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Repository Files
        run: |
          echo "Repository contents:"
          find . -type f

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai colorama

      - name: Validate Inputs
        run: |
          MAX_CALLS="${{ github.event.inputs.max-api-calls }}"
          if ! [[ "$MAX_CALLS" =~ ^[0-9]+$ ]] || [ "$MAX_CALLS" -lt 1 ] || [ "$MAX_CALLS" -gt 60 ]; then
            echo "Error: max-api-calls must be a number between 1 and 60"
            exit 1
          fi
          if [ -z "${{ github.event.inputs.api-key || secrets.GEMINI_API_KEY }}" ]; then
            echo "Error: API key not provided and GEMINI_API_KEY secret not set"
            exit 1
          fi

      - name: Ensure Enhancement Script
        run: |
          if [ ! -f process_files.py ]; then
            echo "Error: process_files.py not found in repository root"
            exit 1
          fi
          chmod +x process_files.py

      - name: Enhance Code
        env:
          GOOGLE_API_KEY: ${{ github.event.inputs.api-key || secrets.GEMINI_API_KEY }}
          MAX_API_CALLS: ${{ github.event.inputs.max-api-calls }}
          FILE_PATTERN: ${{ github.event.inputs.file-pattern }}
        run: |
          ./process_files.py "$(pwd)" "$FILE_PATTERN" > enhancement_log.txt 2>&1 || {
            cat enhancement_log.txt
            exit 1
          }

      - name: Create New Branch and Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          BRANCH_NAME="enhance-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Apply code enhancements"
          else
            echo "No changes to commit"
            exit 0
          fi

      - name: Push Branch
        run: |
          BRANCH_NAME="enhance-$(date +%s)"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "enhance-$(date +%s)"
          title: "Code Enhancements"
          body: |
            This PR contains code enhancements generated by the Gemini API. Please review the changes in the attached `enhancement_log.txt` artifact.
          commit-message: "Apply code enhancements"
          delete-branch: true

      - name: Upload Enhancement Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enhancement-log
          path: enhancement_log.txt
          retention-days: 7
