name: Code Enhancement Workflow
on:
  workflow_dispatch:
    inputs:
      api-key:
        description: 'Gemini API Key (leave blank to use repository secret)'
        required: false
      max-api-calls:
        description: 'Maximum API calls per minute (1-60)'
        required: false
        default: '59'
      file-pattern:
        description: 'File pattern to enhance (must be "*.py" or subpath, e.g., "src/*.py")'
        required: false
        default: '**/*.py'

jobs:
  enhance-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Default Branch
        id: get-default-branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep "HEAD branch" | cut -d' ' -f5)
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT
          echo "Default branch is $DEFAULT_BRANCH"

      - name: List Repository Files
        run: |
          echo "Repository contents:"
          find . -type f

      - name: List Matched Python Files
        run: |
          echo "Matched files for pattern ${{ github.event.inputs.file-pattern }}:"
          find . -type f -path "${{ github.event.inputs.file-pattern }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Validate Inputs
        run: |
          MAX_CALLS="${{ github.event.inputs.max-api-calls }}"
          if ! [[ "$MAX_CALLS" =~ ^[0-9]+$ ]] || [ "$MAX_CALLS" -lt 1 ] || [ "$MAX_CALLS" -gt 60 ]; then
            echo "Error: max-api-calls must be a number between 1 and 60"
            exit 1
          fi
          if [ -z "${{ github.event.inputs.api-key || secrets.GEMINI_API_KEY }}" ]; then
            echo "Error: API key not provided and GEMINI_API_KEY secret not set"
            exit 1
          fi
          FILE_PATTERN="${{ github.event.inputs.file-pattern }}"
          if [[ ! "$FILE_PATTERN" =~ \.py$ ]]; then
            echo "Error: file-pattern must target .py files (e.g., '*.py', 'src/*.py')"
            exit 1
          fi

      - name: Ensure Enhancement Script
        run: |
          if [ ! -f xfix_files.py ]; then
            echo "Error: xfix_files.py not found in repository root"
            exit 1
          fi
          chmod +x xfix_files.py

      - name: Enhance Code
        env:
          GOOGLE_API_KEY: ${{ github.event.inputs.api-key || secrets.GEMINI_API_KEY }}
          MAX_API_CALLS: ${{ github.event.inputs.max-api-calls }}
          FILE_PATTERN: ${{ github.event.inputs.file-pattern }}
        run: |
          ./xfix_files.py "$(pwd)" "$FILE_PATTERN" > enhancement_log.txt 2>&1 || {
            echo "Enhancement script failed:"
            cat enhancement_log.txt || echo "No log generated"
            exit 1
          }

      - name: Ensure Enhancement Log Exists
        run: |
          if [ ! -f enhancement_log.txt ]; then
            echo "No enhancement log generated, creating empty log" > enhancement_log.txt
          fi

      - name: Debug Git Status
        run: |
          git status
          echo "Staged changes:"
          git diff --cached

      - name: Check for Modified Files
        id: check-changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            echo "Files modified by enhancement script"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No files modified"
            if [ -s enhancement_log.txt ]; then
              echo "Error: Enhancement log contains content but no files were modified"
              cat enhancement_log.txt
              exit 1
            fi
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Create New Branch and Commit Changes
        if: steps.check-changes.outputs.changes_detected == 'true'
        id: commit-changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          BRANCH_NAME="enhance-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git commit -m "Apply code enhancements to Python files"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Push Branch
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: |
          git push origin ${{ steps.commit-changes.outputs.branch_name }}

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit-changes.outputs.branch_name }}
          base: ${{ steps.get-default-branch.outputs.default_branch }}
          title: "Code Enhancements for Python Files"
          body: |
            This PR contains code enhancements for Python (.py) files generated by the Gemini API. 
            Please review the changes and the attached `enhancement_log.txt` artifact for details.
          commit-message: "Apply code enhancements to Python files"
          delete-branch: true

      - name: Upload Enhancement Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enhancement-log
          path: enhancement_log.txt
          retention-days: 7
