name: Gemini File Enhancement

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # Needs write permission to push changes

jobs:
  enhance_files_with_gemini:
    name: Enhance Files via Gemini
    runs-on: ubuntu-latest
    concurrency:
      # Group concurrency by workflow and ref to avoid race conditions
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true # Cancel older runs on the same branch

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          # Fetch all history to enable comparing commits accurately
          fetch-depth: 0

      - name: Install Utilities (jq, file)
        run: sudo apt-get update && sudo apt-get install -y jq file

      - name: Configure Git User
        run: |
          # Configure git user for commits made by this action
          git config --global user.name 'Gemini Enhancement Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Process Files with Gemini
        env:
          # Use the Gemini API Key stored as a secret
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Exit script on any error, treat unset variables as errors, propagate pipe failures
          set -eo pipefail
          echo "Starting Gemini file enhancement process..."

          # Declare an array to hold files to process
          declare -a files_to_process

          # Determine the range of commits and identify changed files based on the event type
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Handle the case of the very first push to a branch where 'before' is all zeros
            if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
              echo "Initial push detected. Processing all tracked files in the current commit (HEAD)."
              # Get all files tracked by git in the current commit, null-delimited
              mapfile -d $'\0' files_to_process < <(git ls-tree -r --name-only -z HEAD)
            else
              COMMIT_RANGE="${{ github.event.before }}..${{ github.sha }}"
              echo "Processing changes in push event range: ${COMMIT_RANGE}"
              # Get files added (A) or modified (M) in the commit range, null-delimited for safety
              mapfile -d $'\0' files_to_process < <(git diff --name-only --diff-filter=AM -z "${COMMIT_RANGE}")
            fi
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # For manual trigger, process files changed in the latest commit compared to its parent
            COMMIT_RANGE="HEAD^..HEAD"
            echo "Processing changes in workflow_dispatch event range (last commit): ${COMMIT_RANGE}"
            # Get files added (A) or modified (M) in the last commit, null-delimited
            mapfile -d $'\0' files_to_process < <(git diff --name-only --diff-filter=AM -z "${COMMIT_RANGE}")
          else
            echo "Unsupported event type: ${{ github.event_name }}. Exiting."
            exit 1
          fi

          # Check if any files were identified for processing
          if [[ ${#files_to_process[@]} -eq 0 ]]; then
            echo "No relevant files found to process in the specified range."
            exit 0 # Successful exit, nothing to do
          fi

          echo "Found ${#files_to_process[@]} file(s) to potentially process."

          # Loop through the identified files safely using the array
          for file in "${files_to_process[@]}"; do
            # Trim potential leading/trailing whitespace just in case (though git diff -z shouldn't produce them)
            file=$(echo "$file" | xargs)

            # Ensure file path actually exists as a file and is not empty before proceeding
            if [[ ! -f "$file" ]]; then
               echo "Skipping path (no longer exists or not a file): '$file'"
               continue
            fi
            if [[ ! -s "$file" ]]; then
               echo "Skipping file (empty): '$file'"
               continue
            fi

            # Check if the file is likely text-based using the 'file' command
            mime_type=$(file -b --mime-type "$file")
            # Regex to match common text, code, config, and data formats
            if echo "$mime_type" | grep -q -E '^text/|^application/(json|xml|javascript|x-sh|yaml|toml|csv|x-httpd-php|x-python|x-perl|x-ruby|sql|html|css)'; then
              echo "Processing text-based file: '$file' (Type: $mime_type)"

              # Read file content and escape it properly for JSON embedding using jq
              # jq -Rs reads raw input (-R) as a single string (-s) and JSON-encodes it.
              file_content_escaped=$(jq -Rs '.' "$file")
              if [[ -z "$file_content_escaped" ]]; then
                echo "Warning: Failed to read or encode file content for '$file'. Skipping."
                continue
              fi

              # Construct the JSON payload using heredoc with correct syntax
              # Note: The opening { must be on the line *after* <<EOF
              # Note: The closing EOF must be at the beginning of its own line.
              # Note: Backticks in the prompt are escaped as \\\`
              json_payload=$(cat <<EOF
{
  "contents": [{
    "parts":[{
      "text": "You are an expert code reviewer and enhancer. Analyze the following file content (from file: '${file}'). Focus on quality, clarity, correctness, potential bugs, and adherence to best practices relevant to its likely language or format (e.g., Python, JavaScript, Markdown, YAML). Enhance the content where possible: fix errors, improve style/readability, add necessary comments ONLY if clarity is significantly improved (avoid redundant comments), optimize code (without changing functionality unless fixing a bug), and ensure consistency. Respond ONLY with the complete, enhanced file content. Do not include explanations, apologies, introductory phrases, or markdown formatting like \\\`\\\`\\\` code blocks. Return only the raw, improved file content. If no improvements are necessary, return the original content exactly.\n\nOriginal file content:\n${file_content_escaped}"
    }]
  }],
  "generationConfig": {
    "temperature": 0.4,
    "maxOutputTokens": 8192,
    "topP": 0.95,
    "topK": 40
  },
  "safetySettings": [
     { "category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE" },
     { "category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE" },
     { "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_MEDIUM_AND_ABOVE" },
     { "category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE" }
  ]
}
EOF
              ) # End of heredoc assignment to json_payload

              # Define the API URL (Using gemini-1.5-pro-latest as an example, adjust if needed)
              api_url="https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=${GEMINI_API_KEY}"
              echo "Sending request to Gemini API for '$file'..."

              # Make the API call using curl
              # -s: Silent mode
              # -f: Fail silently (no output) on HTTP errors (status code >= 400)
              # -S: Show error message if -s is used and curl fails
              # -X POST: Specify POST request
              # -H: Set Content-Type header
              # -d: Send data payload
              response=$(curl -sfS -X POST -H "Content-Type: application/json" -d "${json_payload}" "${api_url}")

              # Check curl exit status explicitly
              curl_exit_status=$?
              if [[ ${curl_exit_status} -ne 0 ]]; then
                echo "Error: curl command failed for file '$file' with exit code ${curl_exit_status}. Check API key, URL, network, or payload size. Skipping."
                # Optionally log the (potentially partial) response for debugging, but be careful with sensitive data
                # echo "Failed response snippet: $(echo "$response" | head -c 200)"
                continue # Skip to the next file
              fi

              # Check for API errors explicitly returned in the JSON response
              # Checks for .error.message first, then for safety blocks (.promptFeedback.blockReason)
              api_error=$(echo "${response}" | jq -r '(.error.message // (.promptFeedback.blockReason // ""))')
              if [[ -n "$api_error" ]]; then
                echo "Warning: Gemini API returned an error or block reason for '$file'. Reason: ${api_error}. Skipping."
                # Optionally log the full error response for debugging
                # echo "Full API error response: ${response}"
                continue # Skip to the next file
              fi

              # Extract the enhanced content text safely using jq
              # Uses // empty to return an empty string if the path doesn't exist
              enhanced_content=$(echo "${response}" | jq -r '.candidates[0].content.parts[0].text // empty')

              # Check if the enhanced content is empty
              if [[ -z "$enhanced_content" ]]; then
                echo "Warning: Gemini provided no content (empty response text) for '$file'. This might be due to safety filters or an unexpected API issue. Skipping."
                # Optionally log the full response when content is missing
                # echo "Full API response (empty content): ${response}"
                continue # Skip to the next file
              fi

              # Write enhanced content to a temporary file
              # Using printf is generally safer than echo for arbitrary content
              temp_file="$file.gemini_tmp"
              printf '%s' "$enhanced_content" > "$temp_file"

              # Compare original and enhanced content using cmp (quietly -s)
              if cmp -s "$file" "$temp_file"; then
                echo "No functional changes detected by Gemini for '$file'."
                rm "$temp_file" # Clean up temporary file
              else
                echo "Gemini has refined: '$file'. Applying changes."
                # Overwrite original file with the enhanced version
                mv "$temp_file" "$file"
                # Add the changed file to git staging area immediately
                git add "$file"
              fi

            else
              # Log skipped non-text files
              echo "Skipping file (non-text or excluded type: ${mime_type}): '$file'"
            fi # End of MIME type check

            # Add a small delay to avoid hitting API rate limits too aggressively
            sleep 2
          done # End of file processing loop

          echo "Finished processing potential files."

      - name: Commit and Push Enhancements
        run: |
          # Check if there are any staged changes (files modified by Gemini and added in the loop)
          # Use --cached (or --staged) to check the index/staging area
          if git diff --staged --quiet; then
            echo "No changes were staged by Gemini, nothing to commit."
          else
            echo "Changes detected. Committing Gemini's enhancements..."
            # Commit the staged changes
            # The commit message includes [skip ci] to prevent potential CI loops
            git commit -m "chore: Enhance files via Gemini Bot [skip ci]" \
                       -m "Automated file enhancements applied by the Gemini GitHub Action."

            echo "Pushing changes back to the repository branch: ${{ github.ref_name }}..."
            # Push the commit to the same branch the workflow ran on
            git push origin HEAD:${{ github.ref_name }}
          fi

      - name: Enhancement Process Complete
        run: echo "Gemini file enhancement workflow finished."
