name: Gemini AI Reviewer Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  gemini_code_review:
    name: Run Gemini AI Code Review
    runs-on: ubuntu-latest

    env:
      GEMINI_MODEL: gemini-2.5-pro-exp-03-25 # Updated Gemini model version
      INPUT_EXCLUDE: '' # Exclude specific files or directories if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for accurate review

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure compatibility with the action

      - name: Install Dependencies (Optional)
        run: npm install # Add if dependencies are required for code review

      - name: Run Gemini AI Reviewer
        id: gemini_review
        uses: HoangNguyen0403/gemini-ai-code-reviewer@v0.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ env.GEMINI_MODEL }}
          INPUT_EXCLUDE: ${{ env.INPUT_EXCLUDE }}

      - name: Handle Gemini Review Output
        if: ${{ success() }}
        run: |
          echo "Gemini AI Review completed successfully."
          # Add additional handling logic here if needed

      - name: Log Failure
        if: ${{ failure() }}
        run: |
          echo "Gemini AI Review failed. Check the logs for details."

      - name: Upload Logs (Optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: gemini-review-logs
          path: ./logs # Replace with your actual log path
