name: Gemini AI Reviewer
uses: HoangNguyen0403/gemini-ai-code-reviewer@v0.0.3
with:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GEMINI_MODEL: gemini-1.5-pro-latest
  INPUT_EXCLUDE: ''
