name: Gemini File Enhancement

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  enhance_files_with_gemini:
    name: Enhance Files via Gemini
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Utilities (jq, file)
        run: sudo apt-get update && sudo apt-get install -y jq file

      - name: Configure Git User
        run: |
          git config --global user.name 'Gemini Enhancement Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Process Files with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          set -eo pipefail
          echo "Starting Gemini file enhancement process..."

          if [[ "${{ github.event_name }}" == "push" ]]; then
            COMMIT_RANGE="${{ github.event.before }}..${{ github.sha }}"
            echo "Processing changes in push event range: ${COMMIT_RANGE}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            COMMIT_RANGE="HEAD^..HEAD"
            echo "Processing changes in workflow_dispatch event range (last commit): ${COMMIT_RANGE}"
          else
            echo "Unsupported event type: ${{ github.event_name }}. Exiting."
            exit 1
          fi

          git diff --name-only --diff-filter=AM "${COMMIT_RANGE}" --print0 | while IFS= read -r -d $'\0' file; do
            echo "Processing changed file: $file"

            if [[ -f "$file" && -s "$file" ]] && file -b --mime-type "$file" | grep -q -E '^text/|^application/(json|xml|javascript|yaml|x-sh|toml|csv)'; then
              echo "File identified as text-based. Preparing request for Gemini..."

              file_content=$(jq -Rs '.' "$file")
              if [[ -z "$file_content" ]]; then
                echo "Warning: Failed to read or encode file content for $file. Skipping."
                continue
              fi

              # --- FIX IS HERE ---
              # Ensure <<EOF is followed by a newline, content starts on next line.
              json_payload=$(cat <<EOF
{
  "contents": [{
    "parts":[{
      "text": "You are an expert code reviewer and enhancer. Analyze the following file content (from file: '${file}'). Focus on quality, clarity, correctness, potential bugs, and adherence to best practices relevant to its likely language or format (e.g., Python, JavaScript, Markdown, YAML). Enhance the content where possible: fix errors, improve style/readability, add necessary comments ONLY if clarity is significantly improved (avoid redundant comments), optimize code (without changing functionality unless fixing a bug), and ensure consistency. Respond ONLY with the complete, enhanced file content. Do not include explanations, apologies, introductory phrases, or markdown formatting like \`\`\` code blocks. Return only the raw, improved file content. If no improvements are necessary, return the original content exactly.\n\nOriginal file content:\n${file_content}"
    }]
  }],
  "generationConfig": {
    "temperature": 0.4,
    "maxOutputTokens": 8192,
    "topP": 0.95,
    "topK": 40
  },
  "safetySettings": [
     { "category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE" },
     { "category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE" },
     { "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_MEDIUM_AND_ABOVE" },
     { "category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE" }
  ]
}
EOF
# ^ Closing EOF must be alone at the start of its line
              )
              # --- END FIX AREA ---


              api_url="https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?key=${GEMINI_API_KEY}"
              echo "Sending request to Gemini API for $file..."
              response=$(curl -sfS -X POST -H "Content-Type: application/json" -d "${json_payload}" "${api_url}")

              if [[ $? -ne 0 ]]; then
                echo "Error: curl command failed for file $file. See runner logs for details. Skipping."
                continue
              fi

              api_error=$(echo "${response}" | jq -r '(.error.message // (.promptFeedback.blockReason // empty))')
              if [[ -n "$api_error" ]]; then
                echo "Warning: Gemini API returned an error for $file. Reason: ${api_error}. Skipping."
                continue
              fi

              enhanced_content=$(echo "${response}" | jq -r '.candidates[0].content.parts[0].text // empty')

              if [[ -z "$enhanced_content" ]]; then
                echo "Warning: Gemini provided no content (empty response) for $file. Skipping."
                continue
              fi

              echo "${enhanced_content}" > "$file.gemini_tmp"
              if cmp -s "$file" "$file.gemini_tmp"; then
                echo "No changes detected by Gemini for $file."
                rm "$file.gemini_tmp"
              else
                echo "Gemini has refined: $file. Applying changes."
                mv "$file.gemini_tmp" "$file"
              fi

            else
              if [[ ! -f "$file" ]]; then
                 echo "Skipping changed path (not a file): $file"
              elif [[ ! -s "$file" ]]; then
                 echo "Skipping changed file (empty): $file"
              else
                 mime_type=$(file -b --mime-type "$file")
                 echo "Skipping changed file (non-text or excluded type: ${mime_type}): $file"
              fi
            fi
            sleep 1
          done

          echo "Finished processing changed files."

      - name: Commit and Push Enhancements
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes were made by Gemini, nothing to commit."
          else
            echo "Changes detected. Committing Gemini's enhancements..."
            git add .
            git commit -m "chore: Enhance files via Gemini Bot [skip ci]" \
                       -m "Automated file enhancements applied by the Gemini GitHub Action."
            echo "Pushing changes back to the repository branch: ${{ github.ref_name }}..."
            git push origin HEAD:${{ github.ref_name }}
          fi

      - name: Enhancement Process Complete
        run: echo "Gemini file enhancement workflow finished successfully."
