
name: Pyrmethus Enhancement Workflow

on:
  workflow_dispatch:
    inputs:
      base_directory:
        description: 'Base directory to search for Python files'
        required: true
        default: '.'
      file_pattern:
        description: 'Glob pattern for Python files (e.g., "**/*.py")'
        required: true
        default: '**/*.py'
      google_api_key:
        description: 'Google API Key (leave blank to use repository secret)'
        required: false
      max_api_calls:
        description: 'Maximum API calls per minute (1-60)'
        required: false
<<<<<<< HEAD
        default: '70'
      commit_message:
        description: 'Custom commit message for the enhancement changes'
        required: false
        default: 'Apply Pyrmethus code enhancements'
=======
        default: '59'
      commit_message:
        description: 'Custom commit message for the enhancement changes'
        required: false
        default: 'Apply automated code enhancements'
>>>>>>> 67c3910 (Add GitHub Actions workflows for code enhancement and linting)

jobs:
  enhance_python_code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai aiohttp

      - name: Validate Inputs
        run: |
          FILE_PATTERN="${{ inputs.file_pattern }}"
          if [[ ! "$FILE_PATTERN" =~ \.py$ ]] || [[ "$FILE_PATTERN" =~ \[.*\] ]] || [[ "$FILE_PATTERN" =~ [[:space:]]or[[:space:]] ]]; then
            echo "Error: file_pattern must target .py files (e.g., '*.py', '**/*.py') and not contain square brackets or 'or'"
            echo "Invalid pattern provided: $FILE_PATTERN"
            exit 1
          fi
          MAX_CALLS="${{ inputs.max_api_calls }}"
          if ! [[ "$MAX_CALLS" =~ ^[0-9]+$ ]] || [ "$MAX_CALLS" -lt 1 ] || [ "$MAX_CALLS" -gt 60 ]; then
            echo "Error: max_api_calls must be a number between 1 and 60"
            exit 1
          fi
          if [ -z "${{ inputs.google_api_key || secrets.GOOGLE_API_KEY }}" ]; then
            echo "Error: Google API key not provided and GOOGLE_API_KEY secret not set"
            exit 1
          fi
          if [ ! -d "${{ inputs.base_directory }}" ]; then
            echo "Error: Base directory '${{ inputs.base_directory }}' does not exist"
            exit 1
          fi

      - name: Ensure Enhancement Script
        run: |
          if [ ! -f xfix_files.py ]; then
            echo "Error: xfix_files.py not found in repository root"
            exit 1
          fi
          chmod +x xfix_files.py

      - name: List Repository Files
        run: |
          echo "Repository contents:" | tee -a enhancement_log.txt
          find . -type f | tee -a enhancement_log.txt

      - name: List Matched Python Files
        run: |
          echo "Matched files for pattern ${{ inputs.file_pattern }} in directory ${{ inputs.base_directory }}:" | tee matched_files.txt
          find "${{ inputs.base_directory }}" -type f -path "${{ inputs.file_pattern }}" | tee -a matched_files.txt
          if ! grep -q "[^[:space:]]" matched_files.txt; then
            echo "Warning: No Python files matched the pattern ${{ inputs.file_pattern }} in directory ${{ inputs.base_directory }}" | tee -a matched_files.txt
          fi

      - name: Run Code Enhancement Script
        env:
          GOOGLE_API_KEY: ${{ inputs.google_api_key || secrets.GOOGLE_API_KEY }}
          MAX_API_CALLS: ${{ inputs.max_api_calls }}
        run: |
          touch enhancement_log.txt
          ./xfix_files.py "${{ inputs.base_directory }}" "${{ inputs.file_pattern }}" >> enhancement_log.txt 2>&1 || {
            echo "Error: Enhancement script failed:" >> enhancement_log.txt
            cat enhancement_log.txt
            exit 1
          }

      - name: Debug Git Status
        run: |
          git status | tee -a enhancement_log.txt
          echo "Staged changes:" | tee -a enhancement_log.txt
          git diff --cached || echo "No staged changes" | tee -a enhancement_log.txt

      - name: Check for Changes
        id: git_status
        run: |
          git add .
          if ! git diff --cached --quiet; then
            echo "Changes detected" | tee -a enhancement_log.txt
<<<<<<< HEAD
            echo* echo "changes_made=true" >> $GITHUB_OUTPUT
=======
            echo "changes_made=true" >> $GITHUB_OUTPUT
>>>>>>> 67c3910 (Add GitHub Actions workflows for code enhancement and linting)
          else
            echo "No changes detected" | tee -a enhancement_log.txt
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.git_status.outputs.changes_made == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create New Branch and Commit Changes
        if: steps.git_status.outputs.changes_made == 'true'
        id: commit-changes
        run: |
          BRANCH_NAME="enhance-$(date +%Y%m%d-%H%M%S)-${{ github.run_id }}"
          echo "Creating branch: $BRANCH_NAME" | tee -a enhancement_log.txt
          git checkout -b "$BRANCH_NAME" || {
            echo "Error: Failed to create branch $BRANCH_NAME" | tee -a enhancement_log.txt
            exit 1
          }
          git commit -m "${{ inputs.commit_message }}" || {
            echo "Error: Failed to commit changes" | tee -a enhancement_log.txt
            git status
            exit 1
          }
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Push Changes
        if: steps.git_status.outputs.changes_made == 'true'
        run: |
          BRANCH_NAME="${{ steps.commit-changes.outputs.branch_name }}"
          echo "Pushing branch $BRANCH_NAME to origin" | tee -a enhancement_log.txt
          git push origin "$BRANCH_NAME" --force-with-lease || {
            echo "Error: Failed to push branch $BRANCH_NAME" | tee -a enhancement_log.txt
            git status
            git remote -v
            exit 1
          }

      - name: Create Pull Request
        if: steps.git_status.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit-changes.outputs.branch_name }}
          base: ${{ github.ref_name }}
<<<<<<< HEAD
          title: "Pyrmethus Code Enhancements"
=======
          title: "Automated Code Enhancements"
>>>>>>> 67c3910 (Add GitHub Actions workflows for code enhancement and linting)
          body: |
            This PR contains automated code enhancements for Python (.py) files using the Gemini API.

            **Details:**
            - Base directory: ${{ inputs.base_directory }}
            - File pattern: ${{ inputs.file_pattern }}
            - API calls per minute: ${{ inputs.max_api_calls }}
            - Commit message: ${{ inputs.commit_message }}

            Please review the changes and the attached `enhancement_log.txt` and `matched_files.txt` artifacts.
          labels: |
            enhancement
            automated
          assignees: ${{ github.actor }}
          commit-message: "${{ inputs.commit_message }}"
          delete-branch: true

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enhancement-artifacts
          path: |
            matched_files.txt
            enhancement_log.txt
          retention-days: 7
          if-no-files-found: warn
