name: Ruff Autofix PR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ruff-propose-fixes:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-pr
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Formatter and Linter with Autofix
        id: ruff_autofix
        run: |
          ruff check . --fix --exit-non-zero-on-fix
          echo "Ruff ran with exit code $?"
        continue-on-error: true

      - name: Create Pull Request with fixes
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[Auto] Apply Ruff fixes"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: ruff-fixes/${{ github.head_ref || github.ref_name }}
          branch-suffix: none
          delete-branch: true
          title: '[Auto] Ruff fixes for ${{ github.head_ref || github.ref_name }}'
          body: |
            Ruff autofix identified and applied changes.

            Triggered by commit: `${{ github.sha }}`
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please review and merge.
          labels: autofix, ruff, automated pr
          assignees: ${{ github.actor }}

      - name: Check PR Creation Status and Ruff Outcome
        if: always()
        run: |
          echo "Pull Request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "PR Number: ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "PR Created/Updated: ${{ steps.create_pr.outputs.pull-request-operation }}"
          echo "Ruff Autofix Step Outcome: ${{ steps.ruff_autofix.outcome }}"

          if [[ "${{ steps.ruff_autofix.outcome }}" == "failure" ]]; then
            echo "::error::Ruff step failed, likely due to unfixable errors. Check the logs and the created PR (if any)."
            exit 1
          elif [[ "${{ steps.create_pr.outputs.pull-request-operation }}" == "none" ]]; then
             echo "Ruff ran successfully and no code changes were needed."
          else
             echo "Ruff fixes proposed in PR ${{ steps.create_pr.outputs.pull-request-number }}."
